version: "3.8"

services:
  whoami:
    image: containous/whoami:latest
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.home.rileymathews.com`)
      - traefik.http.routers.whoami.tls.certresolver=le
